name: movna
description: Movna is an open-source training application.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_i18n: ^0.36.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  flutter_map_location_marker: ^10.0.2
  flutter_map_tile_caching: ^10.1.0
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  geolocator: ^13.0.4
  get_it: ^8.0.3
  go_router: ^15.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  json_annotation: ^4.8.1
  json_locale: ^1.0.1
  latlong2: ^0.9.1
  logger: ^2.0.1
  meta: ^1.9.1
  mutex: ^3.0.1
  package_info_plus: ^8.3.0
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^12.0.0+1
  restart_app: ^1.3.2
  result_dart: ^2.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  go_router_builder: ^2.3.0
  injectable_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  json_locale_generator: ^1.0.1
  json_serializable: ^6.7.1
  r_flutter: ^0.9.0
  test: ^1.24.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  default-flavor: dev

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic


json_to_dart:
  sample_files:
    - source: assets/translations/en.json
      class_name: LocaleKeys
      plural_matcher: "-[0-9]+$"