part of 'app_theme.dart';

const _textTheme = TextTheme(
  displayLarge: TextStyle(
    height: 1.12,
    fontWeight: FontWeight.w400,
    fontSize: 57,
    letterSpacing: -0.25,
  ),
  displayMedium: TextStyle(
    height: 1.56,
    fontWeight: FontWeight.w400,
    fontSize: 45,
    letterSpacing: 0,
  ),
  displaySmall: TextStyle(
    height: 1.22,
    fontWeight: FontWeight.w400,
    fontSize: 36,
    letterSpacing: 0,
  ),
  headlineLarge: TextStyle(
    height: 1.25,
    fontWeight: FontWeight.w400,
    fontSize: 32,
    letterSpacing: 0,
  ),
  headlineMedium: TextStyle(
    height: 1.29,
    fontWeight: FontWeight.w400,
    fontSize: 28,
    letterSpacing: 0,
  ),
  headlineSmall: TextStyle(
    height: 1.33,
    fontWeight: FontWeight.w400,
    fontSize: 24,
    letterSpacing: 0,
  ),
  titleLarge: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    height: 1.27,
    letterSpacing: 0,
    wordSpacing: 0,
  ),
  titleMedium: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 16,
    fontWeight: FontWeight.w500,
    height: 1.5,
    letterSpacing: 0.15,
    wordSpacing: 0,
  ),
  titleSmall: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    height: 1.43,
    letterSpacing: 0.1,
  ),
  labelLarge: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    height: 1.43,
    letterSpacing: 0.1,
  ),
  labelMedium: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    height: 1.33,
    letterSpacing: 0.5,
  ),
  labelSmall: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 11,
    fontWeight: FontWeight.w500,
    height: 1.45,
    letterSpacing: 0.5,
  ),
  bodyLarge: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    height: 1.33,
    letterSpacing: 0.5,
  ),
  bodyMedium: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.43,
    letterSpacing: 0.25,
  ),
  bodySmall: TextStyle(
    fontFamily: Fonts.poppins,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.33,
    letterSpacing: 0.4,
  ),
);
