# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    #runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter Version Management CLI
        uses: flutter-actions/setup-fvm@v1.0

      - name: Install Flutter SDK
        run: echo yes | fvm install

      - name: Print Flutter SDK version
        run: fvm flutter --version

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Generate files
        run: fvm dart run build_runner build

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: fvm flutter format --output=none --set-exit-if-changed

      - name: Analyze project source
        run: fvm flutter analyze

      - name: Run tests
        run: fvm flutter test

      # Uncomment to build apk.
      # - name: Build APK
      #  run: fvm flutter build apk
